name: react-hooks-axios

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install 
      - run: npm run build
      - run: npm install -g @jsdevtools/npm-publish
      - run: npm-publish --token=${{ secrets.NPM_TOKEN }} ./package.json